name: Remote Auto-Deploy
on:
  push:
    branches: [ master ] # Changed from main to master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Trigger Updater
        shell: cmd
        run: |
          cd /d "C:\Users\eleeh\Downloads\ytclientV2-2\ytclientV2"
          updater.bat
